### ISSUE TITLE
Errors regarding Making this database in Ubuntu 10.04(64-bit)

### ISSUE THREAD

**Issue by vaibhavthapliyal** [bakks/virginian#2]
Hello Everyone

First of all a massive thanks to the developers of this project. You have created something brilliant. 

However when I tried testing this database on my Linux Machine (Ubuntu 10.04, 64 bit), I get errors during the make.

I edited the makefile as suggested in the readme prior to the make. I am running CUDA 5.5 version and have a Tesla C1060 GPU installed.

I am getting the following errors when I run the makefile in project root directory:

/usr/bin/ld: skipping incompatible ../lib/libgsl.so when searching for -lgsl
/usr/bin/ld: cannot find -lgsl
collect2: ld returned 1 exit status

What I have already tried doing to solve this error but they failed:
1. I have tried to replace the libgsl.so file in the lib folder with its 64 bit version.
2. I have also tried to switch the directory to lib64 in the makefile.
3. I have also tried to make the file without linking the libgsl and libgslcblas files, then I get a different error.

collect2: ld terminated with signal 11 [Segmentation fault]
/usr/bin/ld: i386 architecture of input file `../lib/libgtest.a(gtest-all.o)' is incompatible with i386:x86-64 output

Any help to solve this installation problem would be helpful. Thanks in Advance

Vaibhav

**Comment by rajpatta** [comment]
Hello ,

i have tried compiling the project 
i am stuck at this. 
it would be of great help if you'd let me know what the problem is.

the error shown is as follows:

/usr/bin/ld: skipping incompatible ../lib/libgsl.so when searching for -lgsl
/usr/bin/ld: cannot find -lgsl
/usr/bin/ld: skipping incompatible ../lib/libgslcblas.so when searching for -lgslcblas
/usr/bin/ld: cannot find -lgslcblas
collect2: error: ld returned 1 exit status
make[1]: *** [../release/virginiantest] Error 1
make[1]: Leaving directory `/home/shekhar/virginian-master/src'
make: *** [all] Error 2

**Comment by gamalelkomy** [comment]
Hello Bakks,
I am trying to install the virginian DB on my linux ubuntu 14 (64bit) and I have the same error
/usr/bin/ld: skipping incompatible ../lib/libgsl.so when searching for -lgsl
/usr/bin/ld: cannot find -lgsl
/usr/bin/ld: skipping incompatible ../lib/libgslcblas.so when searching for -lgslcblas
/usr/bin/ld: cannot find -lgslcblas
collect2: error: ld returned 1 exit status
make[1]: *** [../release/virginiantest] Error 1

Could you please help me to fix this problem?

**Comment by bakks** [comment]
@rajpatta @gamalelkomy 

Whenever I've seen this this problem in the past it has stemmed from incompatible architectures between the Virginian compilation and the GSL compilation. Can you experiment with putting `-m32` and `-m64` in this line: https://github.com/bakks/virginian/blob/master/src/Makefile#L19.

Let me know if that has any effect.

**Comment by gamalelkomy** [comment]
Hello Peter,
Thank you for your reply.
I have edited that line and put the

**Comment by bakks** [comment]
@gamalelkomy Hmmm, not sure then. Perhaps you can try installing the gsl package on your system and tweaking the include path in the Virginian make file?

**Comment by gamalelkomy** [comment]
Hello bakks,
I have solved the problem. It needed to install the GNU and refere to the library in the variable LD_LIBRARY_PATH
Thanks :)

**Comment by akashrisrani** [comment]
Hello,
I am still getting the following error:
/usr/bin/ld: i386 architecture of input file `../lib/virginian.a(close.o)' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `../lib/virginian.a(init.o)' is incompatible with i386:x86-64 output

And also lot of undefined references:
tmpxft_00001ab8_00000000-4_vm_gpu.cudafe1.cpp:(.text+0x117): undefined reference to `cudaLaunch'
../lib/virginian.a(vm_gpu.o): In function `virg_vm_gpu':
tmpxft_00001ab8_00000000-4_vm_gpu.cudafe1.cpp:(.text+0x1a6): undefined reference to `cudaMemcpyToSymbol'
tmpxft_00001ab8_00000000-4_vm_gpu.cudafe1.cpp:(.text+0x1ab): undefined reference to `cudaGetLastError'
tmpxft_00001ab8_00000000-4_vm_gpu.cudafe1.cpp:(.text+0x1bf): undefined reference to `cudaStreamCreate'
tmpxft_00001ab8_00000000-4_vm_gpu.cudafe1.cpp:(.text+0x1c4): undefined reference to `cudaGetLastError'

Any help please..
